### ISSUE TITLE
Feature request: move buttons to top of extension

### ISSUE THREAD

**Issue by 33mhz** [lukasz-duda/ErrorIndicator#11]
When enough errors show up, Firefox adds a scroll bar to the list, and the "dismiss" and "turn off" buttons are hidden at the bottom of the page, below the scroll. It would be great to have the buttons stick always in view, either by putting them at the top, or just fixed to the bottom of the addon, not within the scrolled area.

**Comment by lukasz-duda** [comment]
To begin with, I limited the height. Is it enough?
![limit](https://user-images.githubusercontent.com/2528831/198387827-12df547c-c2b2-47ad-bf36-c29a71631b45.png)

**Comment by 33mhz** [comment]
That works for me!
