### ISSUE TITLE
Error types filtering

### ISSUE THREAD

**Issue by rockenren** [lukasz-duda/ErrorIndicator#12]
Hello,

is there any possibility to implement error types filtering (via selectable options maybe)?

For example: I only need to monitor network/web requests errors and nothing more, but for now I must check thru all errors, even if there are no web requests errors at all.

Thank you for this addon, haven't found any like this for such a simple task.

**Comment by lukasz-duda** [comment]
Hi,
Thanks for the feedback. I'll see what I can do.

**Comment by lukasz-duda** [comment]
I've added settings to ignore selected error sources. Try current version 1.12 and let me know if it's enough.
![ignore](https://user-images.githubusercontent.com/2528831/213940915-b4e9de8f-62af-4ba9-8430-8ebceb27eaed.png)

**Comment by rockenren** [comment]
Yes, that's perfectly enough.
Thank you!
