### ISSUE TITLE
No timestamp near error details

### ISSUE THREAD

**Issue by marcin-dolegowski** [lukasz-duda/ErrorIndicator#3]
No timestamp near error details.

**Comment by lukasz-duda** [comment]
This add-on is intended to work with in the current time. But I've decided to add time stamp, as it can be helpful for some. Most developers should be familiar with ISO 8601 format.
![timestamp added](https://cloud.githubusercontent.com/assets/2528831/21751087/544205c6-d5c1-11e6-8350-f0db0abb2e5f.png)
