### ISSUE TITLE
Error details - style

### ISSUE THREAD

**Issue by marcin-dolegowski** [lukasz-duda/ErrorIndicator#4]
Error text should have a margin on the right side.
![issue](https://cloud.githubusercontent.com/assets/24792991/21502490/71d97800-cc50-11e6-97a9-62940f6648ca.png)

**Comment by lukasz-duda** [comment]
This issue has been resolved by [this commit](https://github.com/lukasz-duda/ErrorIndicator/commit/fdb24256a8b7ef4b7b3534371b3aa2d98bf91227). To see current version you can clone the repository and load add-on from source code manually as described [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox).
