### ISSUE TITLE
number of errors

### ISSUE THREAD

**Issue by gotlowski** [lukasz-duda/ErrorIndicator#6]
I can see 332 errors during using firefox for one hour. My suggestion is to remove errors older than genereted 5 minutes ago.

**Comment by lukasz-duda** [comment]
I think it could be strange if someone saw an error, went to the kitchen and when back the error disappeared. The add-on is intended to register all errors and to present them in simple fashion without any grouping or interpretation. But now the switch button has been added, so you can tell to ignore errors when you're not working, by clicking the switch off button in the bottom-left corner.
![timestamp added](https://cloud.githubusercontent.com/assets/2528831/21751244/523c2d12-d5c4-11e6-9895-1d2114eb5024.png)

**Comment by gotlowski** [comment]
Possibility of disable add-on resolving my doubts
